name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: clone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/smpny7/okayama-univ-fes-2021-countdown
      - name: set remote
        run: cd oufes2021-countdown-sample && git remote add upstream https://github.com/oucrc-org/okayama-univ-fes-2021-countdown
      - name: fetch
        run: cd oufes2021-countdown-sample && git fetch upstream
      - name: checkout
        run: cd oufes2021-countdown-sample && git checkout main
      - name: merge
        run: cd oufes2021-countdown-sample && git merge upstream/main
      - name: push
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: cd oufes2021-countdown-sample && git push https://smpny7:${PERSONAL_ACCESS_TOKEN}@github.com/smpny7/okayama-univ-fes-2021-countdown
